Investigate smart dashboard
FRCTeam1024/PowerUp pull request #3
Opened 2018-01-18 01:42 UTC by Javonito

2018-01-18 01:47 UTC, MrDoctorb requested changes
Many of these need added to gitignore

2018-01-18 01:47 UTC, orb102 commented on .classpath
> +	<classpathentry kind="var" path="USERLIBS_DIR/CANJaguar.jar"/>
Delete this.

2018-01-18 01:47 UTC, orb102 commented on .metadata/.log
> +!SESSION 2018-01-16 16:48:13.839 -----------------------------------------------
Add to gitignore

2018-02-06 01:11 UTC, closed without merging

2018-02-06 01:11 UTC, gowabash commented
too out of date